syntax = "proto3";

package torrent;

// Option for Java
option java_multiple_files = true;
option java_package = "org.devMandali.magnetPlay";
option java_outer_classname = "TorrentProto";

// Option for Go
option go_package = "MagnetPlay/backend/proto;torrent";

service TorrentService {
  rpc AddTorrent(TorrentRequest) returns (TorrentResponse);
}

message TorrentRequest {
  string magnetURL = 1;
}

enum TorrentStatus {
  NOT_FOUND = 0;
  SINGLE_FILE = 1;
  MULTI_FILE = 2;
  NON_VIDEO_FILE = 3;
}

message FileInfo {
  string name = 2;
  int64 size = 3;
}

message TorrentResponse {
  string torrentId = 1;
  string name = 2;
  TorrentStatus status = 3;
  repeated FileInfo files = 4;
}
