package torrent

import (
	"context"
	"fmt"
	"log"
	"mime"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"time"

	pb "server/proto"

	lt "github.com/anacrolix/torrent"
)

func InitializeTorrentClient() (*lt.Client, error) {
	clientConfig := lt.NewDefaultClientConfig()
	clientConfig.DataDir = "./downloads"
	client, err := lt.NewClient(clientConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to create libtorrent client: %w", err)
	}
	return client, nil
}

type TorrentService struct {
	client *lt.Client
	pb.UnimplementedTorrentServiceServer

	torrents map[string]*lt.Torrent
	mu       sync.Mutex
}

func NewTorrentService(client *lt.Client) *TorrentService {
	return &TorrentService{
		client:   client,
		torrents: make(map[string]*lt.Torrent),
	}
}

func (s *TorrentService) AddTorrent(ctx context.Context, request *pb.TorrentRequest) (*pb.TorrentResponse, error) {
	magnetURL := request.GetMagnetUrl()

	torrent, ok := s.GetTorrent(magnetURL, "")
	if ok != nil {
		return &pb.TorrentResponse{
			Status: pb.TorrentStatus_NOT_FOUND,
		}, nil
	}
	// Get info hash to use as torrent ID
	infoHash := torrent.InfoHash().String()

	// Torrent is now added and metadata is available, we can extract the information we need to return to the client
	info := torrent.Info()

	// Get torrent name
	name := info.Name
	log.Printf("Torrent name: %s", name)

	// Get list of files in the torrent and their sizes
	torrentFiles := torrent.Files()

	// If files are empty, it might be a single-file torrent
	if len(torrentFiles) == 0 {
		return &pb.TorrentResponse{
			TorrentId: infoHash,
			Name:      name,
			Status:    pb.TorrentStatus_SINGLE_FILE,
		}, nil
	}

	OTHER_VIDEO_TYPES := []string{
		"application/octet-stream",      //often used for video files without a recognized extension
		"application/ogg",               //legacy or highly specialized formats
		"application/mp4",               //legacy or highly specialized formats
		"application/x-mpegURL",         //Streaming Manifests
		"application/vnd.apple.mpegurl", //Streaming Manifests
	}

	// If there are files, it's a multi-file torrent. We need to extract the file paths and sizes
	fileInfoList := make([]*pb.FileInfo, 0)
	for i, file := range torrentFiles {
		// Get extension (e.g., .mp4, .mkv)
		ext := filepath.Ext(file.DisplayPath())

		contentType := mime.TypeByExtension(ext)
		log.Printf("File: %s, Extension: %s, Content-Type: %s", file.DisplayPath(), ext, contentType)

		// If the MIME type is empty, it means we couldn't determine the type based on the extension, we can log a warning and skip it
		if contentType == "" {
			log.Printf("Warning: Unknown MIME type for file %s, skipping", file.DisplayPath())
		}

		// We want to filter out non-video files, we can do this by checking the MIME type of the file based on its extension, if it doesn't start with "video/" and it's not in our list of other video types, we skip it
		if !strings.HasPrefix(contentType, "video/") && !slices.Contains(OTHER_VIDEO_TYPES, contentType) {
			continue
		}

		// Hash for each file can be generated by combining the torrent info hash with the file index, this way we can uniquely identify each file within the torrent
		id := fmt.Sprintf("%s:%d", infoHash, i)
		fileInfoList = append(fileInfoList, &pb.FileInfo{
			Id:   id,
			Name: file.DisplayPath(),
			Size: file.Length(),
		})
	}
	log.Print("Files: ", fileInfoList)

	return &pb.TorrentResponse{
		TorrentId: infoHash,
		Name:      name,
		Files:     fileInfoList,
		Status:    pb.TorrentStatus_MULTI_FILE,
	}, nil
}

// GetTorrent checks if the torrent already exists in the map, if not it adds it and waits for metadata to be available
func (s *TorrentService) GetTorrent(magnetURL string, infoHash string) (*lt.Torrent, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Check if torrent already exists
	if infoHash != "" {
		torrent, exists := s.torrents[infoHash]
		if exists {
			return torrent, nil
		}
	}

	// If not, add it
	torrent, err := s.client.AddMagnet(magnetURL)
	if err != nil {
		return nil, fmt.Errorf("failed to add torrent: %v", err)
	}

	// Wait for metadata
	select {
	case <-torrent.GotInfo():
		// metadata received
	case <-time.After(60 * time.Second):
		return nil, fmt.Errorf("timeout waiting for torrent metadata")
	}

	// Cache it in the map
	s.torrents[torrent.InfoHash().String()] = torrent
	return torrent, nil
}
