server:
  port: 8080

springdoc:
  api-docs:
    path: /magnetplay-api-docs

grpc:
  client:
    TorrentService:
      address: ${GRPC_TORRENT_SERVICE_ADDRESS:static://localhost:50051}
      enable-keep-alive: true
      negotiationType: ${GRPC_NEGOTIATION_TYPE:plaintext}

