syntax = "proto3";

package email;

// Generate Java Code in org.devMandali.email
option java_package = "org.devMandali.email";
option java_multiple_files = true;

// The email service
service EmailService {
  // Send a single email
  rpc SendEmail(SendEmailRequest) returns (SendEmailResponse);
}

// Request to send an email
message SendEmailRequest {
  string to = 1;
  string subject = 2;
  string body = 3;
  string from = 4;
}

// Response after Sending email
message SendEmailResponse {
  bool success = 1;
  string message_id = 2;
  string error = 3;
}

